#ifndef ENUMS_H
#define ENUMS_H

// This file defines the constants used in relationship queries.
// Do not edit this file.

// Genders
enum class Gender 
{
    MAN,
    WOMAN,
    NONBINARY,
    PREFERNOTTOANSWER
};

#endif
